# Site settings
title: Hello from spacebetween
name: Thnkr
email: hello@spacebetween.io
phone: 01233 800991
description: > # this means to ignore newlines until "baseurl:"
  Work with us to solve solutions for real people. Generating measurable value through innovative design and development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thnkr.co.uk" # the base hostname & protocol for your site
twitter_username: space__between
github_username:  spacebetween

# Build settings
markdown: kramdown
